name: Node.js Build+Deploy

on:
  workflow_dispatch

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: 'npm'
    - name: Install npm dependencies
      run: npm install
    - name: Globally configure git user
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    - name: Run deployment script
      run: scripts/gh-pages-deploy.sh
